### ISSUE TITLE
Twitter link not filling out profile

### ISSUE THREAD

**Issue by jmatheson** [jmatheson/OnMe-Backend#21]
Profile (ie name) should be filled out upon linking of Facebook or Twitter. There seems to be a bug (not sure if it is that the account is not linking or the name is not storing).

**Comment by volkzayaz** [comment]
Upon linking new profile we do not fill in user data intentionally. We do so only upon registration.

Here's the use case:

User has name "Joe Swanson" with Picture A on  his FB profile. Upon registration app retrieves this info and sets up his OnMe profile with it. 
Later on User links his Twitter account where his name is stated as Mr. Swansonator with Picture B as a profile picture. 
How do we know which username/picture is preferable? What should we do in this case? 

We implemented strategy: initial configuration wins. Would you like some other strategy with this one @jmatheson, @jidulberger  ?

**Comment by jmatheson** [comment]
I signed up with Twitter, I did not sign up with Facebook.
My info is blank.
I agree we should not overwrite if it is not blank.

**Comment by volkzayaz** [comment]
It may be blank, but may not be blank as well. For example my Twitter account contains avatar picture and real Name as well. 

Another case. User soecifically removed his email, because he does not wanna share it. However if he'd like to link his facebook, email would be automatically filled in once more.

To avoid surprises in data population, I recommend sticking to initial profile data and allowing user to change his OnMe Profile manually (which he can already do).

**Comment by jmatheson** [comment]
I guess i still don't understand.
My account is blank and has no information in it.
I have no name or photo and i was never prompted to enter it when signing up via Twitter.
I also have no phone number or email address for matching friends.
I only have a Twitter handle and that's it.

**Comment by volkzayaz** [comment]
Closing after discussion with @jmatheson

**Comment by jmatheson** [comment]
The first time you Attach an account we should overwrite. Future login and out should not

**Comment by jmatheson** [comment]
Will keep closed in leiu of#47 which is specific to FB
